---
- name: Deploy server-project
  hosts: servers
  become: yes

  tasks:
    - name: Install Docker
      apt:
        name: docker.io
        state: present
        update_cache: yes

    - name: Start Docker service
      ansible.builtin.service:
        name: docker
        state: started
        enable: yes

    - name: Install Docker compose
      apt:
        name: docker-compose
        state: present

    - name: Clone server-project
      git:
        repo: https://github.com/Alexandr-creat/server-project.git
        dest: /home/alexandr/server-project
        force: yes

    - name: Stop old containers
      command: docker-compose down
      args:
        chdir: /home/alexandr/server-project
      ignore-errors: yes

    - name: Run docker-compose
      command: docker-compose up -d
      args:
        chdir: /home/alexandr/server-project
